image: node:latest

stages:
  - build
  - test
  - release

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run build

testing_testing:
  stage: test
  script: npm test

my_release:
  stage: release
  script: npm run release
